services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "prabogo"]

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    depends_on:
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/prabogo:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=prabogo
      - POSTGRES_USER=prabogo
      - POSTGRES_DB=prabogo

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: prabogo
      RABBITMQ_DEFAULT_PASS: prabogo

volumes:
  redis_data:
